Remove problematic context.log call.
Currently logging like this causes NoSuchMethodError.
If we will ever need such trace we can add it later/add something different that works.